accounts/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^registro/$', views.register_user_view, name='accounts.registro'),
    url(r'gracias/(?P<username>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', views.thanks_view, name='accounts.gracias'),
    url(r'^$', views.index_view, name='accounts.index'),
    url(r'^login/$', views.login_view, name='accounts.login'),
    url(r'^logout/$', views.logout_view, name='accounts.logout'),
    url(r'^editar_email/$', views.edit_email_view, name='accounts.editar_email'),
    url(r'^editar_foto/$', views.edit_photo_view, name='accounts.editar_foto'),
    url(r'^editar_contrasena/$', views.edit_password_view, name='accounts.editar_contrasena'),
    url(r'^agregar_direccion/$', views.add_address_view, name='accounts.agregar_direccion'),
    url(r'^editar_direccion/(?P<pk>\d+)/$', views.edit_address_view, name='accounts.editar_direccion'),
    url(r'^password_reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'accounts.password_reset_done', 'template_name': 'accounts/password_reset_form.html'},
        name='accounts.password_reset'),
    url(r'^password_reset_done/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'accounts/password_reset_done.html'},
        name='accounts.password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'accounts/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^password_done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'accounts/password_reset_complete.html'},
        name='password_reset_complete'),
]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # /home/
    url(regex=r'^$', view=views.index_view, name='home'),
]

servifeng/urls.py
# coding=utf-8
"""servifeng URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('home.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^addresses/', include('addresses.url')),
    url(r'^companies/', include('companies.url')),
    url(r'^services/', include('services.url')),
]

if settings.DEBUG:
    # static files (imagenes, css, js, etc)
    urlpatterns.append(
        # /media/:<mixed>path
        url(
            regex=r'^media/(?P<path>.*)$',
            view='django.views.static.serve',
            kwargs={'document_root': settings.MEDIA_ROOT}
        )
    )

accounts/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.gis.db import models
from django.db import models


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    photo = models.ImageField("Foto", upload_to='profiles', blank=True, null=True)
    telephone = models.CharField("Teléfono", max_length=15, blank=True, null=True)
    services = models.IntegerField("Servicios solicitados", null=True, blank=True)
    score = models.FloatField("Calificacion", null=True, blank=True)
    reg_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta(object):
        verbose_name_plural = "Perfil de usuarios"

    def __str__(self):
        return self.user.username

accounts/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.models import User

class EditPasswordForm(forms.Form):
    password_now = forms.CharField(
        label='Contraseña actual',
        min_length=5,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    password = forms.CharField(
        label='Nueva contraseña',
        min_length=5,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    password2 = forms.CharField(
        label='Repetir contraseña',
        min_length=5,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    def clean_password2(self):
        """Comprueba que el password y password2 sean iguales."""
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return password2


class EditPhoto(forms.Form):
    """Editar imagen del perfil"""
    photo = forms.ImageField()


class EditEmailForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        """Obtener request"""
        self.request = kwargs.pop('request')
        super(EditEmailForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email']
        # Comprobar si ha cambiado email
        email_now = self.request.user.email
        username = self.request.user.username
        if email != email_now:
            # Si lo a cambiado, comprobar que no exista en la db.
            # Excluye el usuario actual
            exist = User.objects.filter(email=email).exclude(username=username)
            if exist:
                raise forms.ValidationError('Ya existe un email igual registrado')
        return email


class RegisterUserForm(forms.Form):
    first_name = forms.CharField(
        min_length=5,
        label='Nombre',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        min_length=5,
        label='Apellido',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    """username = forms.CharField(
        min_length=5,
        label='Usuario',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )"""
    email = forms.EmailField(
        label='Correo electrónico',
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label='Password',
        min_length=5,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label='Confirme password',
        min_length=5,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    photo = forms.ImageField(required=False)

    def clean_username(self):
        """Comprueba que no exista un username igual en la db"""
        username = self.cleaned_data['username']
        if User.objects.filter(username=username):
            raise forms.ValidationError('Nombre de usuario ya registrado.')
        return username

    def clean_email(self):
        """Comprueba que no exista un email igual en la db"""
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError('Ya existe un email igual registrado.')
        return email

    def clean_password2(self):
        """Comprueba que el password y password2 sean iguales."""
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError('Los passwords no coinciden')
        return password2

accounts/views.py
# coding=utf-8
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.mail.message import EmailMessage
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.shortcuts import render

from .forms import RegisterUserForm, EditEmailForm, EditPasswordForm, EditPhoto
from .models import UserProfile


# Create your views here.


@login_required
def index_view(request):
    # Si el usuario ya esta logueado, lo direccionamos a index_view
    return render(request, 'accounts/index.html')


def login_view(request):
    """Valida el acceso del usuario"""
    # Si el usuario ya esta logueado, lo direccionamos a index_view
    if request.user.is_authenticated():
        return redirect(reverse('accounts.index'))

    mensaje = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('accounts.index'))
            else:
                # direccionar informando que la cuenta esta inactiva
                mensaje = 'La cuenta se encuentra inactva'
                return render(request, 'accounts/login.html', {'mensaje': mensaje})
        mensaje = 'Nombre de usuario o contraseña no valido'
    return render(request, 'accounts/login.html', {'mensaje': mensaje})


def register_user_view(request):
    """Registro de usuarios"""
    if request.method == 'POST':
        # Si el metodo es post, obtenemos datos del formulario
        form = RegisterUserForm(request.POST, request.FILES)

        # Comprobamos si el formulario es vacio
        if form.is_valid():
            # En caso de ser valido, obtenemos los datos del formulario
            # form.cleaned_data obtiene los datos limpios y los pone en un
            # diccionario con pares clave/valor, donde clave es el nombre del campo
            # del formulario y el valor es el valor si existe.
            cleaned_data = form.cleaned_data
            username = cleaned_data.get('email')
            first_name = cleaned_data.get('first_name')
            last_name = cleaned_data.get('last_name')
            password = cleaned_data.get('password')
            email = cleaned_data.get('email')
            photo = cleaned_data.get('photo')
            # instanciamos un objeto User, con el username y password
            user_model = User.objects.create_user(username=username,
                                                  password=password,
                                                  first_name=first_name,
                                                  last_name=last_name)
            # agregamos email
            user_model.email = email
            # Y guardamos el objeto, esto guardara los datos en la db.
            user_model.save()
            # Ahora, creamos un objeto UserProfile, aunque no haya incluido
            # una imagen, ya quedara la referencia creada en la db.
            user_profile = UserProfile()
            # Al campo user le asignamos el objeto user_model
            user_profile.user = user_model
            # y le asignamos la photo(el campo permite datos null)
            user_profile.photo = photo
            # damos valor de servicios y escore por defecto
            user_profile.services = 0
            user_profile.score = 0.0
            # Por ultimo, guardamos también el objeto UserProfile
            user_profile.save()
            # Ahora direccionaremos a la pagina accounts/gracias.html
            # Pero lo hacemos con un redirect.
            asunto = 'Servifeng'
            mens = 'Se a realizado su registro correctamente su usuario es: ' + username
            mens = mens + r' ingrese a http://127.0.0.1:8000/accounts/'
            mail = EmailMessage(asunto, mens, to=[email, 'servifeng@gmail.com'])
            mail.send()
            return redirect(reverse('accounts.gracias', kwargs={'username': username}))
    else:
        # si el método es GET, instanciamos un objeto RegisterUserForm vacio
        form = RegisterUserForm()
    # Creamos el contexto
    context = {
        'form': form
    }
    # Y mostramos los datos
    return render(request, 'accounts/registro.html', context)


def thanks_view(request, username):
    # Pantalla de agradecimiento por el registro
    return render(request, 'accounts/gracias.html', {'username': username})


def logout_view(request):
    """Desconecta de la aplicacion"""
    logout(request)
    messages.success(request, 'Te has desconectado con exito.')
    return redirect(reverse('accounts.login'))


@login_required
def edit_email_view(request):
    """Editar email del usuario"""
    # Si el método es post, obtenemos datos del formulario
    if request.method == 'POST':
        form = EditEmailForm(request.POST, request=request)
        if form.is_valid():
            request.user.email = form.cleaned_data['email']
            request.user.save()
            messages.success(request, 'El email ha sido cambiado con exito!.')
            return redirect(reverse('accounts.index'))
    else:
        form = EditEmailForm(request=request, initial={'email': request.user.email})
    return render(request, 'accounts/editar_email.html', {'form': form})


@login_required
def edit_password_view(request):
    """Editar el password"""
    # Si el método es post, obtenemos datos del formulario
    if request.method == 'POST':
        form = EditPasswordForm(request.POST)
        if form.is_valid():
            username = request.user.username
            user = authenticate(username=username, password=form.cleaned_data['password_now'])
            if user is None:
                messages.error(request, 'La contraseña actual no coincide')
                return redirect(reverse('accounts.editar_contrasena'))
            request.user.password = make_password(form.cleaned_data['password'])
            request.user.save()
            messages.success(request, 'El password ha sido cambiado con exito!.')
            messages.success(request, 'Es necesario introducir los datos para entrar.')
            return redirect(reverse('accounts.index'))
    else:
        form = EditPasswordForm()
    return render(request, 'accounts/editar_contrasena.html', {'form': form})


@login_required
def edit_photo_view(request):
    """Editar imagen del usuario"""
    if request.method == 'POST':
        form = EditPhoto(request.POST, request.FILES)
        if form.is_valid():
            user_profile = UserProfile.objects.get(pk=request.user.id)
            user_profile.photo.delete()
            user_profile.photo = form.cleaned_data['photo']
            user_profile.save()
            messages.success(request, 'La imagen ha sido cambiada con exito!.')
            return redirect(reverse('accounts.index'))
    else:
        form = EditPhoto()
    return render(request, 'accounts/editar_foto.html', {'form': form})

accounts/templates/accounts/base_accounts.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                <a href="{% url 'accounts.editar_email' %}" class="list-group-item">Editar email</a>
                <a href="{% url 'accounts.editar_contrasena' %}" class="list-group-item">Editar contraseña</a>
                <a href="{% url 'accounts.editar_foto' %}" class="list-group-item">Editar foto</a>
                <a href="{% url 'addresses.agregar_direccion' %}" class="list-group-item">Agregar dirección</a>
            </div>
        </div>
        <div class="col-md-10">
            {% block accounts_content %}{% endblock accounts_content %}
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/editar_contrasena.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Editar contraseña{% endblock title %}

{% block accounts_content %}
    <h2 class="page-header">Editar contraseña</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Actualizar contraseña</button>
        <a href="{% url 'accounts.index' %}" class="btn btn-warning" type="submit">Cancelar</a>
    </form>
{% endblock accounts_content %}

accounts/templates/accounts/editar_email.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Editar email{% endblock title %}

{% block accounts_content %}
    <h2 class="page-header">Editar Email</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Actualizar Email</button>
        <a href="{% url 'addresses.agregar_direccion' %}" class="btn btn-warning" type="submit">Cancelar</a>
    </form>
{% endblock accounts_content %}

accounts/templates/accounts/editar_foto.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Editar Foto{% endblock %}

{% block accounts_content %}
    <h2 class="page-header">Editar foto</h2>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Actualizar Foto</button>
        <a href="{% url 'accounts.index' %}" class="btn btn-warning" type="submit">Cancelar</a>
    </form>
{% endblock accounts_content %}

accounts/templates/accounts/gracias.html
{% extends 'base.html' %}

{% block title %} Gracias por registrarte{% endblock title %}

{% block content %}
    <h2>{{ username }} gracias por registrarte!</h2>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Perfil de usuario{% endblock title %}

{% block accounts_content %}
    <div class="page-header"><h2>Perfil de usuario</h2></div>
    Hola de nuevo {{ user.username }} tus servicios son {{ user.userprofile.services }}
    y tu calificacion es de {{ user.userprofile.score }}<br>
    <div>
        <img src="{{ MEDIA_URL }}{{ user.userprofile.photo }}" alt="Imagen de {{ user.username }}"/>
    </div>
{% endblock accounts_content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="page-header"><h2>Login</h2></div>
            {% if mensaje %}
                <div class="alert alert-danger">
                    {{ mensaje }}
                </div>
            {% endif %}

            <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" for="username">Correo:</label>
                    <input type="text" id="username" name="username" class="form-control" value="{{ username }}">
                </div>
                <div class="form-group">
                    <label for="password">Contraseña:</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Iniciar sesión</button>
            </form>
            <br>
            <a href="{% url 'accounts.password_reset' %}" class="password-reset-link">¿Has olvidado la cuenta?</a>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Restablecimiento de contraseña completa{% endblock %}

{% block content %}
    <p>La contraseña se ha establecido . Usted puede seguir adelante y acceder ahora.</p>
    <p><a href="{{ login_url }}">Login</a></p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Configuración de Nueva contraseña{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="page-header"><h2>Restablecer la contraseña</h2></div>
            {% if validlink %}
                <p>Por favor, introduzca su nueva contraseña dos veces.<br/>
                    Así podemos comprobar que ha escrito la forma adecuada.</p>
                <form action="" method="post">
                    <div style="display:none">
                        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
                    </div>
                    <table>
                        <tr>
                            <td>{{ form.new_password1.errors }}
                                <label for="id_new_password1">Nueva contraseña:</label></td>
                            <td>{{ form.new_password1 }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.new_password2.errors }}
                                <label for="id_new_password2">Confirmar contraseña:</label></td>
                            <td>{{ form.new_password2 }}</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <button type="submit" class="btn btn-warning">Cambiar contraseña</button>
                            </td>
                        </tr>
                    </table>
                </form>
            {% else %}
                <h1>Restablecimiento de contraseña sin éxito.</h1>
                <p>El enlace de restablecimiento de contraseña no es válido, <br/>
                    posiblemente debido a que ya se ha utilizado. <br/>
                    Solicita un nuevo restablecimiento de contraseña.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block title %}Restablecimiento de contraseña con éxito.{% endblock %}

{% block content %}
    <p>Le hemos enviado por correo electrónico las instrucciones para configurar su contraseña</p>
    <p>Usted debe estar recibiendo en breve.</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load url from future %}
{% autoescape off %}
    You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

    Please go to the following page and choose a new password:
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'django.contrib.auth.views.password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}

    Your username, in case you've forgotten: {{ user.username }}

    Thanks for using our site!

    The {{ site_name }} team.

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block title %}Restablecer la contraseña{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="page-header"><h2>Restablecer la contraseña</h2></div>
            <p>Por favor, indique su dirección de correo electrónico para recibir instrucciones de reinicio.</p>
            <form action="" method="post">
                <div style="display:none">
                    <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
                </div>
                {{ form.email.errors }}
                <p>
                <div class="form-group">
                    <label class="control-label" for="id_email">Correo:</label>
                    {{ form.email }}
                    <button type="submit" class="btn btn-warning">Restablecer</button>
                </div>

                </p>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/registro.html
{% extends 'base.html' %}

{% block title %}Registro de usuario{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="page-header">
                <h2>Registro Usuario</h2>
            </div>

            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>
{% endblock content %}